#!/usr/bin/env bash
set -euo pipefail

# Every released SDK names its own version in X-Custd-Sdk, which is how Custd
# reports which releases actually call it. The constants are generated by
# scripts/bump-version.sh, so a release that forgets one would ship a client that
# misreports itself and quietly corrupts the usage data the platform relies on.

repo_root="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}"
version="$(tr -d '[:space:]' < "${repo_root}/VERSION")"
failures=0

check() {
  local file="$1" pattern="$2" label="$3"
  local found
  found="$(sed -nE "s/.*${pattern}.*/\1/p" "${repo_root}/${file}" | head -1)"
  if [ "${found}" != "${version}" ]; then
    printf '%s: identity constant is %s, VERSION is %s\n' "${label}" "${found:-missing}" "${version}" >&2
    failures=1
  fi
}

check "sdk-go/version.go" "const Version = \"([0-9]+\\.[0-9]+\\.[0-9]+)\"" "sdk-go"
check "sdk-php/src/CustdClient.php" "public const VERSION = \"([0-9]+\\.[0-9]+\\.[0-9]+)\"" "sdk-php"
check "sdk-js/src/version.ts" "export const SDK_VERSION = \"([0-9]+\\.[0-9]+\\.[0-9]+)\"" "sdk-js"
check "sdk-python/src/custd/version.py" "VERSION = \"([0-9]+\\.[0-9]+\\.[0-9]+)\"" "sdk-python"

if [ "${failures}" -ne 0 ]; then
  printf 'Run scripts/bump-version.sh %s to realign the identity constants.\n' "${version}" >&2
  exit 1
fi

printf 'SDK identity constants report version %s\n' "${version}"
